
Get http://localhost:3000/api/QuanLyNguoiDung
Content-Type: application/json



###
get http://localhost:3000/ping


------------------------- Quan Ly Nguoi Dung ------------------------------
###
//Dang ky
POST  http://localhost:3000/api/QuanLyNguoiDung/DangKy
Content-Type: application/json

{
  "taiKhoan": "bang",
  "matKhau": "1234567",
  "email": "phibansg451@gmail.com",
  "soDt": "121225",
  "hoTen": "string"
}


###
//Dang nhap
POST  http://localhost:3000/api/QuanLyNguoiDung/DangNhap
Content-Type: application/json

{
  "taiKhoan" : "bang",
  "matKhau": "1234567"
}


###
//Lay Loai Nguoi Dung 
GET  http://localhost:3000/api/QuanLyNguoiDung/LayDanhSachLoaiNguoiDung

###
//Lay Loai danh sach nguoi dung
GET http://localhost:3000/api/QuanLyNguoiDung/LayDanhSachNguoiDung?tuKhoa=&maNhom=GP01

###
//tìm kiềm người dùng
GET http://localhost:3000/api/QuanLyNguoiDung/TimKiemNguoiDung?tuKhoa=bang

###
//lấy danh sách người dùng phân trang
GET http://localhost:3000/api/QuanLyNguoiDung/LayDanhSachNguoiDungPhanTrang



###
//Lấy Thông tin tài khoản
get http://localhost:3000/api/QuanLyNguoiDung/ThongTinTaiKhoan
accessToken: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidGFpS2hvYW4iOiJiYW5zZzUzNSIsImxvYWlOZ3VvaUR1bmciOiJLaGFjaEhhbmciLCJlbWFpbCI6InBoaWJhbnNnNDU3NTFAZ21haWwuY29tIiwiaWF0IjoxNjQ0Njc3OTY3LCJleHAiOjE2NDQ3NjQzNjd9.X05t6_rJyRRMDV5JQjJPbeVJcstDWpCIDR-FwElWKPE


###
//Lthêm người dùng
POST  http://localhost:3000/api/QuanLyNguoiDung/ThemNguoiDung
accessToken: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidGFpS2hvYW4iOiJiYW5nIiwibG9haU5ndW9pRHVuZyI6IlF1YW5UcmkiLCJlbWFpbCI6ImJhbmdAZ21haWwuY29tIiwiaWF0IjoxNjQ0NjgwMTk4LCJleHAiOjE2NDQ3NjY1OTh9.VGmw14VeCRwNoh_ScK9hXuiRWa6hfP4XoC9TGJa3jQU
Content-Type: application/json

{
  "taiKhoan": "bang10",
  "matKhau": "1234597",
  "email": "phibansg@gmail.com",
  "soDt": "51212265",
  "hoTen": "string",
  "maLoaiNguoiDung": "QuanTri"
}
###

------------------------- Quan Ly Phim ------------------------------
###
//lấy danh sách banner
GET http://localhost:3000/api/QuanLyPhim/LayDanhSachBanner

###
//lấy danh sách Phim
GET http://localhost:3000/api/QuanLyPhim/LayDanhSachPhim?tenPhim=spider-man





------------------------- Quan Ly Rap ------------------------------
###
//lấy thông tin hệ thống rạp
GET http://localhost:3000/api/QuanLyRap/LayThongTinHeThongRap?maHeThongRap=CGV


###
//lấy tông tin cụm rạp theo hệ thống
GET http://localhost:3000/api/QuanLyRap/LayThongTinCumRapTheoHeThong?maHeThongRap=CGV