
Get http://localhost:3000/api/QuanLyNguoiDung
Content-Type: application/json



###
get http://localhost:3000/ping


------------------------- Quan Ly Nguoi Dung ------------------------------
###
//Dang ky
POST  http://localhost:3000/api/QuanLyNguoiDung/DangKy
Content-Type: application/json

{
  "taiKhoan": "bansg535",
  "matKhau": "1263222",
  "email": "phibansg45751@gmail.com",
  "soDt": "12121925",
  "hoTen": "string"
}


###
//Dang nhap
POST  http://localhost:3000/api/QuanLyNguoiDung/DangNhap
Content-Type: application/json

{
  "taiKhoan" : "bansg535",
  "matKhau": "1263222"
}


###
//Lay Loai Nguoi Dung 
GET  http://localhost:3000/api/QuanLyNguoiDung/LayDanhSachLoaiNguoiDung

###
//Lay Loai danh sach nguoi dung
GET http://localhost:3000/api/QuanLyNguoiDung/LayDanhSachNguoiDung?tuKhoa=&maNhom=GP01

###
//tìm kiềm người dùng
GET http://localhost:3000/api/QuanLyNguoiDung/TimKiemNguoiDung?tuKhoa=bang

###
//lấy danh sách người dùng phân trang
GET http://localhost:3000/api/QuanLyNguoiDung/LayDanhSachNguoiDungPhanTrang