
Get http://localhost:3000/api/QuanLyNguoiDung
Content-Type: application/json



###
get http://localhost:3000/ping


------------------------- Quan Ly Nguoi Dung ------------------------------
//Dang ky
###
POST  http://localhost:3000/api/QuanLyNguoiDung/DangKy
Content-Type: application/json

{
  "taiKhoan": "bang113",
  "matKhau": "123122",
  "email": "phibang51@gmail.com",
  "soDt": "1212162",
  "hoTen": "string"
}